process.env.TZ = 'UTC'
process.env.NEXT_PUBLIC_SUPABASE_URL ??= 'https://example.supabase.co'
process.env.SUPABASE_JWT_SECRET ??= 'test-jwt-secret'
process.env.SUPABASE_SERVICE_ROLE_KEY ??= 'test-service-role-key'
process.env.STRIPE_SECRET_KEY ??= 'sk_test_1234567890'
process.env.STRIPE_WEBHOOK_SECRET ??= 'whsec_test_1234567890'
